name = "Trickshot"
uid = "25D57D85-7D84-27HT-A501-TRICKSHOT0002"
version = 2
copyright = "© 2019–2020 Sean Wheeldon"
description = "Adds a UEF mobile tactical missile defense."
author = "Balthazar"
icon = "/mods/FAFTrickshot/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
