rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\Antimass"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\CrystalHill"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\InvisibleWar"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\Knives"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\ScathingBeetles"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\SuddenDeath"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\SuperWonder"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\WonkyResources"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\WreckageDecay"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Gameplay\AcidPools"

rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Plenae"

rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_RNG\CrateDrop"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_RNG\LuckyDip"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_RNG\RPS"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_RNG\TierShift"

rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Units\BrewResearch"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN_Units\BrewReinforce"

rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN\modules\BrewGantries"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN\modules\BrewGantry1"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN\modules\BrewGantry2"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN\modules\BrewGantry3"
rmdir /Q /S "E:\2.Pacchetto mod SCFA\Nuove versioni\BrewLAN\modules\BrewAI"