name = "M27AI"
uid = "f27c55b4-v006-45b4-92b6-64398e75e23f"
version = 6 --REMINDER: Remove ConExecute("WLD_GameSpeed 10"); Version reference in uid updated? Tested offline vs AI it should beat to check for any last minute errors introduced?
copyright = "FreeWare"
description = "Intended for 10x10 and 5x5 1v1 land maps (other maps and teams aren't supported yet). In the early stages of development but should be playable.  Report any bugs to maudlin27 (via forum or discord). V5 - Various bug fixes; Improved ACU logic - ACU is more aggressive, better at expanding, and less suicidal.  See forum for more details. (v6 - Hotfix for new patch)"
author = "maudlin27" --With thanks to Softles/Softlnoob for original Micro AI that was used as a starting point as I learned how to code AI
url = "https://forum.faforever.com/topic/2373/ai-development-guide-and-m27ai-v1-devlog"
icon = "/mods/M27AI/M27AI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
