name = "All Faction Quantum Gate"
uid = "8b2d7222-e15d-42d5-9c4d-29e9fff00002"
version = 2
copyright = "None"
description = "Quantum Gates will build engineers drones and SCU of all FOUR factions. Created by jayTAC"
author = "jayTAC"
selectable = true
enabled = true
exclusive = false
ui_only = false
icon = "/mods/All_Faction_Quantum_Gate/mod_icon.png"