name = "Ultra Shields Tweaked"
uid = "11D16292-3506-11EB-8B52-B6E9FB2CA371"
icon = "/mods/Ultra_Shields_Tweaked/mod_icon.png"
version = 1
copyright = ""
description = "Tweaked version of Ultra Shields(by FreyaGroup). t2 Aeon shields Can be upgraded to t3 and all heavy shields upgradable to Experimental. Each faction has their own bonus."
author = "Coolev009, Original by FreyaGroup"
hookdir = "/hook"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {}
