name = "Storage x2"
uid = "A46094AE-26EC-11E4-AFB3-C91A1E5D46B0"
version = 1
description = "Storage (X2)"
author = "Ghaleon"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
