name = "MAXI Nuclear Repulsor Shields MAXI"
uid = "44844B72-6054-3656-0230-D5FA6066FB5E-MAXI"
version = 23
copyright = "2016-2022 Uveso"
description = "(For all gameversions) Experimental shields with nuclear repulsor technology, so nuke missiles can't penetrate them."
author = "Uveso"
url = "https://forum.faforever.com/topic/357"
icon = "/mods/NuclearRepulsorShields/NukRepShield.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
