name = "Nvidia fix"
uid = "e0b7022c-948f-11eb-a8b3-0242ac130003"
version = 7
description = "Automatically runs a console command for you at the start of every match to fix the nvidia drivers pointer issue. Essentially a modified version of the unlimited FPS mod."
author = "Laticlave"
icon = "/mods/nvidia fix/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
