name = "GGA Seraphim T4 Reclaimer"
uid = "d51bf5cf-e665-48e5-b924-63afadd8ff26"
version = 7
copyright = "bbkineebee"
description = "Seraphim T4 Reclaimer -- reclaim and assist things super quickly. Built in mass storage and energy storage + intel."
author = "bbkineebee - Green Grocers Alliance (GGA)"
icon = "/mods/GGASeraphimT4Reclaimer/GGASeraphimT4Reclaimer_icon.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
