name = "Additional Camera Stuff v3.3"
version = 3
copyright = "Do whatever you want with it, feel free to add stuff, copy, edit, delete code or publish own versions"
description = "Multiple things regarding worldview, minimap and camera actions. Version 3.3 brings support for reclaim range rings when using attack move."
author = "Myxir, Anihilnine, BlackYps"
uid = "71a26460-ec4e-11ea-adc1-0242ac120002"
icon = "/mods/additionalCameraStuff/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
