name = "Anti Nuke price v3.1"
uid = "a3ec424c-d3d6-4775-9303-9372817f2808"
version = 3.1
copyright = ""
description = "Changes AntiNuke missile cost and buildtime to 10% of original to allow games against multiple AIx"
author = "Eni & Brute51"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
