# autogenerated file - DO NOT EDIT THIS FILE UNDER ANY CIRCUMSTANCES
# USE LocStrings.xls INSTEAD TO EDIT STRINGS

expshdaeon001_desc="Experimentální Generátor Štítů"
expshdaeon001_help="Experimentální Generátor Štítů"
expshdaeon001_name="Oslnění"

expshduef001_desc="Experimentální Generátor Štítů"
expshduef001_help="Experimentální Generátor Štítů"
expshduef001_name="ESD Pulse"

expshdcyb001_desc="Experimentální Generátor Štítů"
expshdcyb001_help="Experimentální Generátor Štítů"
expshdcyb001_name="ED6"

expshdser001_desc="Experimentální Generátor Štítů"
expshdser001_help="Experimentální Generátor Štítů"
expshdser001_name="Athanuhthethuum"

ability_hugeshielddome="Obrovský štítový dóm"
