name = "AllFactionsFixed"
uid = "58c232c2-f7e8-4256-8892-85fbb9687a69"
version = 1
copyright = "Copyright © 2008, Legion Darrath"
description = "Spawns the ACU's of all factions. You need to turn on prebuild units for this mod to work, fixed icon by CommanderShepard"
author = "Legion Darrath"
icon = "/mods/AllFactionsFixed/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
