name = "Wyvern Battle Pack"
uid = "9a9C61C0-1787-10DF-A0AD-BATTLEPACK004"
version = 4
copyright = "2010 Brandon Potter"
description = "Contains several new units, effects and projectiles. With full AI support"
author = "Brandon Potter"
url = ""
icon = "/mods/BattlePack/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
