name = "Wyvern Battle Pack MAXI"
uid = "9a9C61C0-1787-10DF-A0AD-BATTLEPACK005-MAXI"
version = 5
copyright = "2010 Brandon Potter"
description = "Contains several new units, effects and projectiles. With full AI support"
author = "Brandon Potter"
url = "https://forum.faforever.com/topic/362/"
icon = "/mods/BattlePack/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
