name = "10% Particles"
uid = "d271e9b0-a464-4c96-8695-788e09e503a6"
version = 1
copyright = ""
description = "reduces particle density to .1"
author = "cino"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}