name = "Anti Nuke price"
uid = "77778cf2-9b8b-11dc-8314-0800200c9a66"
version = 2
copyright = ""
description = "Changes AntiNuke missile cost and buildtime by /10 to allow games against multiple AIx"
author = "Eni"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
